# Thai Content Sources Configuration
# Diverse content sources for social media content creation
# Last verified: 2025-11-30

sources:
  # ✅ VERIFIED WORKING FEEDS - NEWS
  
  - name: "Manager Online - News"
    type: "rss"
    url: "https://mgronline.com/rss/news.xml"
    category: "news"
    country: "TH"
    language: "th"
    description: "Manager Online General News"
    
  - name: "Manager Online - Entertainment"
    type: "rss"
    url: "https://mgronline.com/rss/entertainment.xml"
    category: "entertainment"
    country: "TH"
    language: "th"
    description: "Manager Online Entertainment News"
  
  # ✅ LIFESTYLE & INTERESTING CONTENT
  
  - name: "Bangkok Post - Life"
    type: "rss"
    url: "https://www.bangkokpost.com/rss/data/life.xml"
    category: "lifestyle"
    country: "TH"
    language: "en"
    description: "Bangkok Post Lifestyle - Arts, Entertainment, Social trends (English)"
    
  - name: "Bangkok Post - Most Recent"
    type: "rss"
    url: "https://www.bangkokpost.com/rss/data/most-recent.xml"
    category: "news"
    country: "TH"
    language: "en"
    description: "Bangkok Post Latest Updates (English)"
  
  # ✅ COMMUNITY & VIRAL CONTENT
  
  - name: "Reddit - Thailand"
    type: "rss"
    url: "https://www.reddit.com/r/Thailand/.rss"
    category: "community"
    country: "TH"
    language: "en"
    description: "Reddit Thailand community - Viral posts, discussions, local stories"
    
  - name: "Pantip - Food Forum"
    type: "rss"
    url: "https://www.pantip.com/forum/food/feed"
    category: "food"
    country: "TH"
    language: "th"
    description: "Pantip Food Forum - Restaurant reviews, recipes, food trends"

  # 📝 NOTES:
  # - Bangkok Post provides English content (good for international audience)
  # - Reddit r/Thailand has viral stories, expat perspectives, trending topics
  # - Pantip forums are Thai community discussions (authentic local voice)
  # - Mix of Thai and English content for diverse social media posts
  
  # ❌ BROKEN FEEDS (Removed):
  # - ThaiPBS News/Lifestyle (404)
  # - Sanook News/Lifestyle (404)
  # - Kapook News/Lifestyle (404)
  # - Thairath Online (504 timeout)
  # - Khaosod (connection error)
