# Thai News Sources Configuration
# Only verified working RSS feeds
# Last verified: 2025-11-30

sources:
  # ✅ VERIFIED WORKING FEEDS
  
  - name: "Manager Online - News"
    type: "rss"
    url: "https://mgronline.com/rss/news.xml"
    category: "news"
    country: "TH"
    language: "th"
    description: "Manager Online General News"
    
  - name: "Manager Online - Entertainment"
    type: "rss"
    url: "https://mgronline.com/rss/entertainment.xml"
    category: "entertainment"
    country: "TH"
    language: "th"
    description: "Manager Online Entertainment News"

# Note: Other Thai news sources' RSS feeds are currently unavailable (404)
# ThaiPBS, Sanook, Kapook feeds are not working as of 2025-11-30
